name: Publicar videos en Telegram

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  publicar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Usar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar bot
        run: npm start
        env:
          TELEGRAM_VIDEO_BOT: ${{ secrets.TELEGRAM_VIDEO_BOT }}
          TELEGRAM_GROUP_1: ${{ secrets.TELEGRAM_GROUP_1 }}
          TELEGRAM_GROUP_2: ${{ secrets.TELEGRAM_GROUP_2 }}
          TELEGRAM_GROUP_3: ${{ secrets.TELEGRAM_GROUP_3 }}
          TELEGRAM_GROUP_4: ${{ secrets.TELEGRAM_GROUP_4 }}
          TELEGRAM_GROUP_5: ${{ secrets.TELEGRAM_GROUP_5 }}
          TELEGRAM_GROUP_6: ${{ secrets.TELEGRAM_GROUP_6 }}
          TELEGRAM_GROUP_7: ${{ secrets.TELEGRAM_GROUP_7 }}
